### ISSUE TITLE
Support CocoaPods

### ISSUE THREAD

**Issue by louy** [react-native-text-input-mask/react-native-text-input-mask#103]
Hi,

Is there any reason why this library isn't using CocaPods?

Would you guys be open for PRs adding a podspec file?

**Comment by frangeris** [comment]
@louy Do you have any fork with this support?

**Comment by LRNZ09** [comment]
This would be really useful.

**Comment by kdawgwilk** [comment]
I have a fork I have been maintaining with CocoaPods support, check the `support_cocoapods` branch https://github.com/kdawgwilk/react-native-text-input-mask/tree/support_cocoapods

**Comment by kdawgwilk** [comment]
This really should be a priority now with RN 0.60 that now uses CocoaPods by default

**Comment by joaovpmamede** [comment]
@kdawgwilk to use your fork is just a matter of running `pod install`?
