### ISSUE TITLE
 No known class method for selector 'maskValueWithText:format:'

### ISSUE THREAD

**Issue by Hanums** [react-native-text-input-mask/react-native-text-input-mask#112]
iOS project build fails after recent XCode upgrade from 8 to 10

Here are error details, please help.

Build target RNTextInputMask of project RNTextInputMask with configuration Debug

 error: no known class method for selector 'maskValueWithText:format:'
    NSString *output = [RNMask maskValueWithText:inputValue format:maskString];

error: no known class method for selector 'unmaskValueWithText:format:'
    NSString *output = [RNMask unmaskValueWithText:inputValue format:maskString];

warning: incompatible pointer types initializing 'RCTUITextField *' with an expression of type 'UIView<RCTBackedTextInputViewProtocol> *' [-Wincompatible-pointer-types]
            RCTUITextField *textView = [view backedTextInputView];
                            ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~

error: no visible @interface for 'MaskedTextFieldDelegate' declares the selector 'initWithFormat:'
            MaskedTextFieldDelegate* maskedDelegate = 
error: no known instance method for selector 'setListener:'
            [masks[key] setListener:self];
                        ^~~~~~~~~~~

 warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        [maskedDelegate textField:(UITextField*)textView
        ^
2 warnings and 4 errors generated.

**Comment by ivanzotov** [comment]
@Hanums could you check this out on the new version v1.0.1, please?

**Comment by chemanth** [comment]
@Hanums Modified Swift Language Version for InputMask.xcodeproj to Swift 4.2. The error disappeared. I have selected Swift 5 earlier which caused this error.

**Comment by lhuazai** [comment]
Has anyone solved this problem?
