### ISSUE TITLE
 DYLD, [0x4] Symbol missing

### ISSUE THREAD

**Issue by edxe** [react-native-text-input-mask/react-native-text-input-mask#114]
After updating XCode to latest and the upgrading to the 0.9.0 version i get the following error

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FALLBACK_LIBRARY_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 11.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks

Dyld Error Message:
 Symbol not found: _$sBOWV
 Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/687AD3DB-1970-4780-BB76-80D3246E70A0/data/Containers/Bundle/Application/8901B743-DC39-4894-943B-ED1A7465F420/xxxx_mobile.app/Frameworks/InputMask.framework/InputMask
 Expected in: /Users/USER/Library/Developer/CoreSimulator/Devices/687AD3DB-1970-4780-BB76-80D3246E70A0/data/Containers/Bundle/Application/8901B743-DC39-4894-943B-ED1A7465F420/xxxx_mobile.app/Frameworks/libswiftCore.dylib
in /Users/USER/Library/Developer/CoreSimulator/Devices/687AD3DB-1970-4780-BB76-80D3246E70A0/data/Containers/Bundle/Application/8901B743-DC39-4894-943B-ED1A7465F420/xxxx_mobile.app/Frameworks/InputMask.framework/InputMask

**Comment by ivanzotov** [comment]
@edxe could you check this out on the new version v1.0.1?
