### ISSUE TITLE
Value binding not working(iOS)

### ISSUE THREAD

**Issue by ivan3177** [react-native-text-input-mask/react-native-text-input-mask#118]
I bind value of TextInputMask like this:

`value={this.state.phone === ""
            ? null
            : this.state.phone}`

However it doesn't work. Value property is updated, but old text is still showing. Any ideas how to fix? I guess problem is with value being set to undefined in index.js :
` value={undefined}`

https://github.com/react-native-community/react-native-text-input-mask/blob/2b60c445574f1a5be22872888cc7c76eead76783/index.js#L52

UPD: No, it's not in index.js. I think it's not even in javascript part.

UPD: Issue relates only to iOS. Works fine on Android. Should be somewhere in iOS native part. Need further digging

**Comment by devmathiusso** [comment]
It's not working on Android for me. Value binding works normally with TextInput React Native component, but not with TextInputMask component...

**Comment by duduneto** [comment]
If you change line 52 (node_module/react-native-text-input-mask), it's may work.
Like This
`value={this.props.value}`
It's work for me, and I could set a value to my TextInputMask Component

**Comment by duduneto** [comment]
Actually you could use this

`value={this.props.mask ? this.props.masked : this.props.value}`

This way you will have fewer bugs, if you want maintain the Components that haven't mask
