### ISSUE TITLE
SWIFT_VERSION '3.0' is unsupported, supported version are: 4.0, 4.2, 5.0. (in target 'Flash Chat') for Xcode 10.2.1

### ISSUE THREAD

**Issue by AronnoDIU** [react-native-text-input-mask/react-native-text-input-mask#119]
Already I'm tried with given solutions on this site for this problems. and it's not working with the updated Xcode version. that's why, I want a proper solution for this problem. So please help me out.
<img width="999" alt="Screen Shot 2019-04-30 at 2 24 10 AM" src="https://user-images.githubusercontent.com/20730108/56924603-1f844180-6aef-11e9-821f-3b1a1b4ed13d.png">

**Comment by jerearaujo03** [comment]
Did you solved it?

**Comment by fabioars** [comment]
Same issue here!

**Comment by nikbelikov** [comment]
no hope

**Comment by martintreurnicht** [comment]
Try the latest version, should be working
