### ISSUE TITLE
Build Failed on IOS - The “Swift Language Version” (SWIFT_VERSION)

### ISSUE THREAD

**Issue by lfoliveir4** [react-native-text-input-mask/react-native-text-input-mask#132]
# Bug

  After installing and linking to the library, and following the unique procedure for IOS, when I 
  go to build the library I am presented with the following error below:

## React native info output:

 ![Captura de Tela 2019-07-20 às 04 17 48](https://user-images.githubusercontent.com/32423942/61575698-5f7f1300-aaa5-11e9-95c0-7ead98e59953.png)

## Environment info

"react": "16.8.6",
"react-native": "0.59.3",
Xcode: 9.2
Command Line Tools: 9.4

## Library version:
"react-native-text-input-mask": "^1.0.1",

## Steps To Reproduce

1. react-native run-ios

**Comment by victormoya** [comment]
Same issue here!

**Comment by akhil-geekyants** [comment]
Facing the same issue.
