### ISSUE TITLE
componentWillReceiveProps is deprecated and will be removed in the next major version of RN

### ISSUE THREAD

**Issue by Bruno-Furtado** [react-native-text-input-mask/react-native-text-input-mask#133]
# Feature Request

Use static `getDerivedStateFromProps` instead of `componentWillReceiveProps`.

## Why it is needed

`componentWillReceiveProps` is deprecated and will be removed in the next major version of React Native.

## Possible implementation

Replace the function.

**Comment by cnrsbtogll** [comment]
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: TextInputMask

**Comment by rafael-camara** [comment]
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: TextInputMask

I also get the same answer

I also get the same answer, but I decided following the guidelines at: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path

topic:

- **16.3:** Introduce aliases for the unsafe lifecycles, `UNSAFE_componentWillMount`, `UNSAFE_componentWillReceiveProps`, and `UNSAFE_componentWillUpdate`. (Both the old lifecycle names and the new aliases will work in this release.)

**Comment by ElliDy** [comment]
@iagormoraes can you please mention it here, if you have finished the merge request [142](https://github.com/react-native-community/react-native-text-input-mask/pull/142)

**Comment by bruxalldev** [comment]
Hi any update on this being released? many thanks

**Comment by kjmendoza** [comment]
Hey, everybody, any idea when the update on this case is coming out?

**Comment by bruxalldev** [comment]
The project maintainers are really busy - and you know they are doing this for free - final releases needs the core team to make sure it’s all good.

But I too am waiting on this so I've just created a local version and updated it with the fixes in the commit - index.js.

In a nutshell.. create a folder in your app - called node-modules-local

Download the repository into this folder

Update the index.js file with the the fix for componentWillUpdate

Then update your package.json to point react-native-text-input to the node-modules-local version.

Sure it’s ugly but if you need it now….

**Comment by iagormoraes** [comment]
Guys for the temporary fix use my branch as package source on package.json:

`
"react-native-text-input-mask": "https://github.com/iagormoraes/react-native-text-input-mask"
`

**Comment by SrBrahma** [comment]
Still hapening

**Comment by andraderaul** [comment]
Hello, any updates for this issue?

**Comment by ankorGH** [comment]
@andraderaul  #141  is not released. 
Sharing my current solution till it is released.
1.
```
yarn add patch-package postinstall-postinstall
```
2. Update package.json
```
 "scripts": {
  "postinstall": "patch-package"
 }
```
3. Create a folder called `patches` and inside it create a file called `react-native-text-input-mask+2.0.0.patch`
4. Place the code below
```
diff --git a/node_modules/react-native-text-input-mask/index.js b/node_modules/react-native-text-input-mask/index.js
index 408edad..93388e9 100644
--- a/node_modules/react-native-text-input-mask/index.js
+++ b/node_modules/react-native-text-input-mask/index.js
@@ -34,15 +34,15 @@ export default class TextInputMask extends Component {
     }
   }
 
-  componentWillReceiveProps(nextProps) {
-    if (nextProps.mask && (this.props.value !== nextProps.value)) {
-      mask(this.props.mask, '' + nextProps.value, text =>
+  componentDidUpdate(prevProps) {
+    if (this.props.mask && (prevProps.value !== this.props.value)) {
+      mask(prevProps.mask, '' + this.props.value, text =>
       this.input && this.input.setNativeProps({ text })
       );
     }
 
-    if (this.props.mask !== nextProps.mask) {
-      setMask(findNodeHandle(this.input), nextProps.mask)
+    if (prevProps.mask !== this.props.mask) {
+      setMask(findNodeHandle(this.input), this.props.mask)
     }
   }
```
5. run `yarn`
