### ISSUE TITLE
React Native 0.60 not work

### ISSUE THREAD

**Issue by aspidvip** [react-native-text-input-mask/react-native-text-input-mask#135]
# Bug
Hello!
This component not work is RN 60

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by russelRajitha** [comment]
Working in android and giving warning, but ios its crashing app.

**Comment by betoharres** [comment]
this kind of issues shouldn't be allowed, it's poorly edited and it gives no insight whatsoever.

I'm using 0.60.5 on Android and it's working. No warnings. 
I'm going to text on iOS later and I'll try to update this.

**Comment by igortupini** [comment]
> this kind of issues shouldn't be allowed, it's poorly edited and it gives no insight whatsoever.
> 
> I'm using 0.60.5 on Android and it's working. No warnings.
> I'm going to test on iOS later and I'll try to update this.

How your test went on iOS? I'm considering upgrading my project to 0.60.5 and I'm checking if my libs are compatible.

**Comment by betoharres** [comment]
Hi @igortupini the library does not have a podspec, it will throw an error about mask property of undefined.
I’ll try to use react native link to see if it works; 

I tried to use a solution posted here on a issue called “Cocoapods support” but I had no luck :( Im too noob with xcode

**Comment by betoharres** [comment]
`react-native link` did not worked, well I see this library does not support react-native 0.60. I'd like to submit a PR if anyone is willing to help me with some directions. I'm a completely noob in this subject :(

**Comment by betoharres** [comment]
Hi @ivanzotov , sorry to bother you, would you be able to help us with this? :) Thanks

**Comment by betoharres** [comment]
after more digging I found this close issue https://github.com/react-native-community/react-native-text-input-mask/issues/130#issuecomment-511185054

This lib was made with swift and auto linking supports only obj-c :(

**Comment by waqas19921** [comment]
@betoharres if you add following two lines in header search path
```
$(SRCROOT)/../../../ios/Pods/Headers/Public
$(SRCROOT)/../../../ios/Pods/Headers/Public/React
```
with mode `recursive`
and change the imports in RNTextInputMask.m from 
```
#import <RCTText/RCTBaseTextInputView.h>
#import <RCTText/RCTUITextField.h>
```
to 
```
#import "RCTBaseTextInputView.h"
#import "RCTUITextField.h"
```
It will work with `RN 0.60.5` with manual integration.
Usage with pods will not work as currently the swift code or usage of frameworks is not supported  in `RN 0.60.5`. Need to wait for following pull request to be released.
https://github.com/facebook/react-native/pull/25619

**Comment by waqas19921** [comment]
I will also create a pull request today if i got time.

**Comment by russelRajitha** [comment]
> @betoharres if you add following two lines in header search path
> 
> ```
> $(SRCROOT)/../../../ios/Pods/Headers/Public
> $(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core
> ```
> 
> with mode `recursive`
> and change the imports in RNTextInputMask.m from
> 
> ```
> #import <RCTText/RCTBaseTextInputView.h>
> #import <RCTText/RCTUITextField.h>
> ```
> 
> to
> 
> ```
> #import "RCTBaseTextInputView.h"
> #import "RCTUITextField.h"
> ```
> 
> It will work with `RN 0.60.5` with manual integration.
> Usage with pods through auto linking will not work as currently the swift code or usage of frameworks is not supported in `RN 0.60.5`. Need to wait for following pull request to be released.
> [facebook/react-native#25619](https://github.com/facebook/react-native/pull/25619)

where to put this?
> $(SRCROOT)/../../../ios/Pods/Headers/Public
> $(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core

**Comment by betoharres** [comment]
> > @betoharres if you add following two lines in header search path
> > ```
> > $(SRCROOT)/../../../ios/Pods/Headers/Public
> > $(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core
> > ```
> > 
> > 
> > with mode `recursive`
> > and change the imports in RNTextInputMask.m from
> > ```
> > #import <RCTText/RCTBaseTextInputView.h>
> > #import <RCTText/RCTUITextField.h>
> > ```
> > 
> > 
> > to
> > ```
> > #import "RCTBaseTextInputView.h"
> > #import "RCTUITextField.h"
> > ```
> > 
> > 
> > It will work with `RN 0.60.5` with manual integration.
> > Usage with pods through auto linking will not work as currently the swift code or usage of frameworks is not supported in `RN 0.60.5`. Need to wait for following pull request to be released.
> > [facebook/react-native#25619](https://github.com/facebook/react-native/pull/25619)
> 
> where to put this?
> 
> > $(SRCROOT)/../../../ios/Pods/Headers/Public
> > $(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core

![example](https://i.imgur.com/DcZ10PT.jpg)

I believe it's here, but I still couldn't get it working :(

**Comment by waqas19921** [comment]
@betoharres See setup first line for iOS here:
https://github.com/react-native-community/react-native-text-input-mask#setup

That is you have to do following step mentioned in above link

**iOS only**: you have to drag and drop InputMask.framework to Embedded Binaries in General tab of Target

**Comment by betoharres** [comment]
@waqas19921 Thanks! Somehow I missed it that step! 😄

**Comment by PetrVasilev** [comment]
I have the same problem =(

**Comment by rahsheen** [comment]
[The fix above](https://github.com/react-native-community/react-native-text-input-mask/issues/135#issuecomment-524177774) definitely resolved this long-standing issue for me on RN 0.60.5. Thanks, @waqas19921!

**Comment by k3ithl1m** [comment]
Am currently using the newest version of react native  0.60.5, but am getting the error 
`React/RCTBridge.h file not found`

Did not have this error before upgrading.

Some solution that I tried were:
https://stackoverflow.com/questions/50453883/react-native-build-failed-react-rctbridge-h-file-not-found/50460552

However, the top solution, when I went into manage scheme. There is no React, and it also says React(missing). There is a React-Core, and I tried using that, however the project still fails

also followed this link
getsentry/sentry-react-native#395 (comment)
but did not work

**Comment by luiswouters** [comment]
> I also created a pull request of above changes here
> #137

Now that the pull request has been accepted and the changes merged, I updated my module directly from Github and, doing the manual integration + "dragging and dropping InputMask.framework to Embedded Binaries in General tab of Target" worked for me.

**Comment by waqas19921** [comment]
@k3ithl1m If you are upgrading from react-native version less than `0.60` you have to remove manual linking of libraries in iOS project and use pod file and run `pod install` for dependency management.

**Comment by joaovpmamede** [comment]
@waqas19921 when you run `pod install` do you get this warning:
`[!] use_native_modules! skipped the react-native dependency 'react-native-text-input-mask'. No podspec file was found.`?

**Comment by ThomasStubbe** [comment]
Is there any update on this? When will React 60+ be supported?

**Comment by k3ithl1m** [comment]
Hey @waqas19921, I'm not upgrading from a lesser version. I did the manual link but i still seem to get the same error 'React/RCTBridge.h file not found' 

I manually installed, it didnt work, so i tried calling pod install. But it is still failing. 

Thanks again for working on this. I really appreciate it a lot. Let me know what I could do to help to fix this issue.

**Comment by spasecadet** [comment]
@waqas19921 version 2.0.0 not available via npm.  Can you please make it a release?

**Comment by waqas19921** [comment]
@spasecadet i am not the owner of this package. Only owner can do that.
For `RN 0.60` you can add 
`"react-native-text-input-mask": "react-native-community/react-native-text-input-mask",`
in the `package.json` file.
and remaining steps of installation will be that same.

**Comment by sabun123** [comment]
Thank you for the PR you made @waqas19921

I'm upgrading from RN 0.59.9 to RN 0.60.5.
This last library is currently the show stopper.

In my package.json, I'm pointing to:
"react-native-text-input-mask": "https://github.com/react-native-community/react-native-text-input-mask#abf0e7f"

I'm pinning it to the commit that merged your PR since I don't want bleeding edge master all the  time.

```yarn install``` and then run it (tried both via terminal and Xcode) but am not able to get my app working.

Xcode is returning the following on app start:
```
[error][tid:com.facebook.react.JavaScript] null is not an object (evaluating '_reactNative.NativeModules.RNTextInputMask.mask')
```

I have InputMask.framework inside Embedded Binaries and Linked Frameworks and Libraries. I also have it in Link Binary With Libraries.

Just to note, before upgrading this setup worked. Any ideas what I may be doing wrong or missed?

**Comment by betoharres** [comment]
@sabun123 Thanks a lot for the detailed post, I really appreciate! =] I upgraded to react-native 0.61.1. so do you think that using this version would help me in any way of using this library? They say they fixed `use_frameworks!` CocoaPods support. :thinking:

**Comment by joaoguilhermee** [comment]
Does someone know another plugin for same propose?

**Comment by douglaszaltron** [comment]
+1

**Comment by waqas19921** [comment]
Everyone please test following pull request code https://github.com/react-native-community/react-native-text-input-mask/pull/140, which includes pods integration.
By running `yarn waqas19921/react-native-text-input-mask`

It is working fine with RN `0.61.1`. Need to verify it with `0.60.*`

**Comment by chispalex89** [comment]
i get: 

> [!] Unable to find a specification for `RNInputMask` depended upon by `RNTextInputMask`

after doing pod install

**Comment by betoharres** [comment]
@waqas19921 would you mind share why we need to create the `Dummy.swift` file? Can I delete after building successfully? I don't get it :( Thanks!

**Comment by betoharres** [comment]
Quick Tip for those who wants to install @waqas19921 fork but wants to keep the dependency at the exact commit that he fixed the Pod support. Run the command like this:

`yarn add waqas19921/react-native-text-input-mask#ce7a78f`

`#ce7a78f` is his last commit at this time of writing.

**Comment by betoharres** [comment]
Hey all, I wanted to confirm that @waqas19921 fork works on iOS, I've followed the instructions and everything worked. The only thing that concerns me is that `Dummy.swift` file hanging in there on Xcode.
I'll test on Android to see if everything is still working, which shouldn't be a problem since iOS was the only one giving trouble.

**Comment by rahsheen** [comment]
> Does someone know another plugin for same propose?

I have switched to [react-native-masked-text](https://github.com/benhurott/react-native-masked-text). It's not perfect, but at least it doesn't prevent us from building/deploying our app.

**Comment by conectcell** [comment]
> @betoharres if you add following two lines in header search path
> 
> ```
> $(SRCROOT)/../../../ios/Pods/Headers/Public
> $(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core
> ```
> 
> with mode `recursive`
> and change the imports in RNTextInputMask.m from
> 
> ```
> #import <RCTText/RCTBaseTextInputView.h>
> #import <RCTText/RCTUITextField.h>
> ```
> 
> to
> 
> ```
> #import "RCTBaseTextInputView.h"
> #import "RCTUITextField.h"
> ```
> 
> It will work with `RN 0.60.5` with manual integration.
> Usage with pods through auto linking will not work as currently the swift code or usage of frameworks is not supported in `RN 0.60.5`. Need to wait for following pull request to be released.
> [facebook/react-native#25619](https://github.com/facebook/react-native/pull/25619)

GOD bless you, man. 
It worked not only for input mask, but for all the libraries without podfiles.
One thing - you have to add this search pass to the library project itself, not for your root project.

**Comment by shkatulo** [comment]
> i get:
> 
> > [!] Unable to find a specification for `RNInputMask` depended upon by `RNTextInputMask`
> 
> after doing pod install

It works if you link it like this:

`  pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`

**Comment by waqas19921** [comment]
@chispalex89 you have to follow the readme file.

**Comment by waqas19921** [comment]
@betoharres updated the readme file in #140 . We need `Dummy.swift` as on `RN 0.60` we cannot use `use_frameworks!`. But for any one using `RN 0.60.1` or greater version no need of `Dummy.swift`.
I have mentioned the instructions in readme file in #140 .

**Comment by betoharres** [comment]
@waqas19921 Thanks for the info! Great work!

**Comment by midoalone** [comment]
@waqas19921 Thanks, your fork working great, hope the original library get updated soon.

**Comment by iagorm** [comment]
> @betoharres updated the readme file in #140 . We need `Dummy.swift` as on `RN 0.60` we cannot use `use_frameworks!`. But for any one using `RN 0.60.1` or greater version no need of `Dummy.swift`.
> I have mentioned the instructions in readme file in #140 .

@waqas19921 using your fork, I got an error while running the command `pod install`:
```
[!] Unable to find a specification for `RNInputMask` depended upon by `react-native-text-input-mask`
```

**Comment by iagorm** [comment]
> @betoharres updated the readme file in #140 . We need `Dummy.swift` as on `RN 0.60` we cannot use `use_frameworks!`. But for any one using `RN 0.60.1` or greater version no need of `Dummy.swift`.
> I have mentioned the instructions in readme file in #140 .

@waqas19921 by using and following the readme of your fork the build worked! great work!

**Comment by gabeDevlift** [comment]
@waqas19921 How do I use your pull request? I've never done that before. Like, how do I pull and get it?

**Comment by mikedemarais** [comment]
@gabeDevlift 

hey!
just change your `react-native-text-input-mask` entry in `package.json` to
```
"react-native-text-input-mask": "waqas19921/react-native-text-input-mask"
```


you can read more about all the things you can do inside `package.json` here: https://docs.npmjs.com/files/package.json#dependencies

**Comment by waqas19921** [comment]
@blueberry6401 Please also add `use_frameworks!` in pod file.
And make sure you have followed the instructions from https://github.com/waqas19921/react-native-text-input-mask/blob/master/README.md

**Comment by blueberry6401** [comment]
> @blueberry6401 Please also add `use_frameworks!` in pod file.
> And make sure you have followed the instructions from https://github.com/waqas19921/react-native-text-input-mask/blob/master/README.md

Adding use_frameworks! creates some build error that I don't remember exactly, but after time struggling I made this worked!

**Comment by karmil32** [comment]
> Everyone please test following pull request code #140, which includes pods integration.
> By running `yarn add waqas19921/react-native-text-input-mask`
> 
> It is working fine with RN `0.61.1`. Need to verify it with `0.60.*`

Now i get error while compiling on iOS.

`The 'Pods-AppName' target has transitive dependencies that include static binaries: (/AppPath/ios/Pods/Crashlytics/iOS/Crashlytics.framework and /AppPath/ios/Pods/Fabric/iOS/Fabric.framework)`

I know that's related to Crashlytics but don't how to fix it.

**Comment by arisferyanto** [comment]
@karmil32 I'm using RN `0.61.5`, but I followed the instruction "For RN = 0.60.*" and it is working fine for me. No need to use `use_frameworks!`.

**Comment by johhansantana** [comment]
I am getting a `framework not found InputMask` after following the instructions for 0.60.*

Should I use @waqas19921 repository or use this one since I see the instructions are the same on both.

I'm currently using 
```"react-native-text-input-mask": "2.0.0"```

**Comment by jonatasnardi** [comment]
In react-native 0.62 I just added this line below to Podfile and ran `pod install`:

`pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`

And now it works for me :)

**Comment by IgorDePaula** [comment]
> In react-native 0.62 I just added this line below to Podfile and ran `pod install`:
> 
> `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`
> 
> And now it works for me :)

I tryed with 61.5 and given error compilation

**Comment by linbo8303** [comment]
> > In react-native 0.62 I just added this line below to Podfile and ran `pod install`:
> > `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`
> > And now it works for me :)
> 
> I tryed with 61.5 and given error compilation

Same issue with error compilation in 0.62 unless adding Dummy.swift file

**Comment by soueverest** [comment]
I'm using 0.60.4 and I still can't. I've tried almost everything that I could found. Any ideas?

**Comment by betoharres** [comment]
setup a new project with this library, it will help ypu identify your problem

**Comment by likewagon** [comment]
I am using Xcode 11.6 and react-native-text-input-mask:2.0.0
It works well on simulator and real iPhone.
but when I plugged new iPhone (iOS 13.6), I got error.

RNInputMask modulemap not found

**Comment by iagormoraes** [comment]
> I am using Xcode 11.6 and react-native-text-input-mask:2.0.0
> It works well on simulator and real iPhone.
> but when I plugged new iPhone (iOS 13.6), I got error.
> 
> RNInputMask modulemap not found

try to install the package from my repository:

"react-native-text-input-mask" :"https://github.com/iagormoraes/react-native-text-input-mask"

**Comment by rubycop** [comment]
Adding 
```
use_modular_headers!
```
in Podfile works for me. RN "0.69.3"
