### ISSUE TITLE
Is there a way to update the mask dynamically

### ISSUE THREAD

**Issue by acollazomayer** [react-native-text-input-mask/react-native-text-input-mask#138]
Is there a way to update the mask dynamically. I save the mask in the store, but in the rerender the mask does not change

**Comment by performatric** [comment]
Hello, is there any workaround?

**Comment by Tohid1999** [comment]
i update Mask by useState and its work

**Comment by AlexandrDobrovolskiy** [comment]
I'm updating my mask with state and it causes onBlur and onEndEditing to stop working
