### ISSUE TITLE
(iOS) `TextInputMask` doesn't update the masked value after component did mount

### ISSUE THREAD

**Issue by AlimovSV** [react-native-text-input-mask/react-native-text-input-mask#14]
Any `TextInputMask.value` property changes does not have any affects to masked value. Android works fine.

**Comment by AlimovSV** [comment]
Also doesn't work selectTextOnFocus={true}.

**Comment by ivanzotov** [comment]
@AlimovSV Thanks for the issue, will try to fix

**Comment by igortupini** [comment]
Any update on this?

**Comment by martintreurnicht** [comment]
This should be fixed in [V3](https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.0)
