### ISSUE TITLE
IOS build failed 'Undefined symbols for architecture x86_64' #387

### ISSUE THREAD

**Issue by fgagneten** [react-native-text-input-mask/react-native-text-input-mask#152]
I upgraded to version 2.0.0 because of the following error: https://github.com/react-native-community/react-native-text-input-mask/pull/140

After that, I started to get the following error:
 
![image](https://user-images.githubusercontent.com/14353978/74176759-1a742700-4c17-11ea-8be3-87e9d4dffe79.png)

![image](https://user-images.githubusercontent.com/14353978/73678551-5e0ae600-4697-11ea-8b3f-9fec571f1fd4.png)

I tried to restart XCode, clean an rebuild but nothing worked.

This is how my Podfile ends:

    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party- podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    use_frameworks!
    pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

    use_native_modules!
    end

React Native Version: "0.61.5",
react-native-text-input-mask Version: "2.0.0"

**Comment by fgagneten** [comment]
Someone found any solution for this?

**Comment by hardywu** [comment]
Same here.

**Comment by ElizavetaDevel** [comment]
the same issue

**Comment by francozini2** [comment]
Please fix this issue I have the same issue!

**Comment by ElizavetaDevel** [comment]
I found solution, add duumy.swift file with bridging header to your ios project (it is described in readme)

**Comment by danghung24031992** [comment]
> I found solution, add duumy.swift file with bridging header to your ios project (it is described in readme)

Thank bro

**Comment by cKurultayKalkan** [comment]
@ElizavetaDevel Thank You!

**Comment by martintreurnicht** [comment]
This issue should no longer exist

**Comment by juanjavc06** [comment]
> This issue should no longer exist

We are talking about Apple. The must expensive but cheaper platform.

**Comment by haduy97** [comment]
I've the same issue and this [Solution](https://stackoverflow.com/questions/71933392/react-native-ios-undefined-symbols-for-architecture-x86-64) worked really well for me
