### ISSUE TITLE
'RCTBaseTextInputView.h' file not found

### ISSUE THREAD

**Issue by nihp** [react-native-text-input-mask/react-native-text-input-mask#153]
I ran into issue while building my app using this package. 

```
react-native-cli: 2.0.1
react-native: 0.59.8
```

I have used manual linking for this . https://www.npmjs.com/package/react-native-text-input-mask#ios-2

Anyone have solution.

Here I tried with 
1. rm -rf node_modules
2. Clean the build folder
3. Close xcode
4. Re-run the app

Still facing the same issue.

**Comment by panda919** [comment]
Honest, It is very dirty plugin.
I have been used this plugin in 2 years, and try to me best to keep it.
But this plugin has fatal ios issue, and they can not fix it yet.
I recommend to use https://github.com/benhurott/react-native-masked-text.

**Comment by leiyuanyi** [comment]
![image](https://user-images.githubusercontent.com/12016806/97593363-95e36600-1a3c-11eb-9dfb-d85e61ccb60f.png)
Try to update your bulid config
