### ISSUE TITLE
Support Windows platform

### ISSUE THREAD

**Issue by giregk** [react-native-text-input-mask/react-native-text-input-mask#154]
# Feature Request
I would love this module to work with react-native-windows (0.61+).

I've tried to build a simple version of it following their documentation, but I'm not skilled enough in C# or C++ to do it. (But I'd be very glad to help if someone helps me get started).

**Comment by martintreurnicht** [comment]
I'd recommend reaching out to https://github.com/RedMadRobot/. This is a simple wrapper, if they supported the native platform, we could add RN support pretty easily
