### ISSUE TITLE
RN 0.61.5 null is not a object

### ISSUE THREAD

**Issue by danghung24031992** [react-native-text-input-mask/react-native-text-input-mask#156]
I try install but not done   . Pls support for me.thanks
![Simulator Screen Shot - iPhone 8 - 2020-04-10 at 16 39 05](https://user-images.githubusercontent.com/9923258/78981344-edc28a00-7b49-11ea-88c5-c2d450dcaa83.png)

**Comment by tugzera** [comment]
Same here!!!

**Comment by samuelcp** [comment]
I tried add the following to `PodFile` and it works

```
pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'
```

**Comment by tugzera** [comment]
@samuelcp Updated my packange and change on pod.. Then works !! THx

**Comment by nutrimax1987** [comment]
omg , library so small and so much issues .

**Comment by jairolima** [comment]
Same here

**Comment by karanmartian** [comment]
Same issue, not working on Android.

**Comment by IgorMing** [comment]
Me too! Same issue.
That's working on iOS, but not working on Android.

**Comment by Escalion86** [comment]
Same issue on Android =(

**Comment by Seaghan-dev** [comment]
Any updates on this issue? I'm also facing this problem in android :(

**Comment by leovieira** [comment]
Still does not work!

**Comment by martintreurnicht** [comment]
Should be working, p;lease try the latest version

**Comment by Worik42** [comment]
same issue Android!

**Comment by jpcastro4** [comment]
Same issue Android

**Comment by LiamAshdown** [comment]
Same issue Android

**Comment by dnp1** [comment]
Same issue here

**Comment by leandro-almeida98** [comment]
Mesmo problema, não funciona.

**Comment by ErickJ3** [comment]
Same issue here
