### ISSUE TITLE
please change to function

### ISSUE THREAD

**Issue by secodigo** [react-native-text-input-mask/react-native-text-input-mask#158]
please change to function, instead of class, is generating warning 
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

**Comment by walterholohan** [comment]
https://github.com/react-native-community/react-native-text-input-mask/pull/141 should solve this warning however there seems to be no-one with write access to merge the changes.
