### ISSUE TITLE
Swift Compiler Error: Missing required module 'Combine'

### ISSUE THREAD

**Issue by DivinoMatheus** [react-native-text-input-mask/react-native-text-input-mask#167]
Someone can help me with this? 

I'm using xcode 10.1 with SWIFT 5 by hacking xcode like in [this tutorial](https://learningswift.brightdigit.com/swift-5-0-xcode-10-1/)

I cannot update the xcode because the lastest supported version of macOS in my computer is 10.13.6 and i need to use version 10.14.3 or later to xcode 10.2 be compatible.

![image](https://user-images.githubusercontent.com/27539713/88923371-fe595600-d247-11ea-901f-a687140e66fc.png)

**Comment by yanakievv** [comment]
Did you fix it? Got the same problem here.

**Comment by akimabs** [comment]
hey, how do you resolve this issue ?
