### ISSUE TITLE
Two kind of Mask in One Input

### ISSUE THREAD

**Issue by CarlosDanielDev** [react-native-text-input-mask/react-native-text-input-mask#168]
# Feature request

This feature will help us to put 2 kind of mask in one input, fpor example, email or phone number.

## Why it is needed

If I has just one field to put information about the user, I'd like to give him a choice, choose email or phone number ?

## Possible implementation

On mask prop will receive 2 positions in a array, if him type a number, apply the mask of phone number, if him type some character, apply de mask of email.

### Code sample

```tsx
<TextInput
   mask={['[(00)] [0000] [0000]', '[xxxxx]@[xxxxx]']}
/>
```

**Comment by martintreurnicht** [comment]
Native libraries does support multiple masks, happy to support the feature if you want to put a PR together
