### ISSUE TITLE
Cannot read property 'mask' of undefined when using jest

### ISSUE THREAD

**Issue by costagolub** [react-native-text-input-mask/react-native-text-input-mask#17]
Having a problem with running jest tests. It failed with the TypeError 
`Cannot read property 'mask' of undefined`
Are there any suggestions or workarounds how this could be solved?

**Comment by ArmandoAssuncao** [comment]
You have mock the package, like:
```
// __mocks__/react-native-text-input-mask.js
import React from 'react'

class TextInputMask extends React.Component {
    render() {
        return null
    }
}

const mask = (mask, value, cb ) => {}
const unmask = (mask, masked, cb ) => {}
const setMask = (node, mask) => {}

export { mask, unmask, setMask }
export default TextInputMask
```

**Comment by betoharres** [comment]
Thanks @ArmandoAssuncao !! :smile:
This should be on the README.
Can I send a PR adding this?

**Comment by martintreurnicht** [comment]
This is a common pattern that you would need to use with all native modules and is not specific to this project
