### ISSUE TITLE
How to disable mask?

### ISSUE THREAD

**Issue by Gentlee** [react-native-text-input-mask/react-native-text-input-mask#171]
I have type='custom' and mask, and i want to be able to disable this mask.

What prop should i pass to this buggy piece of component?

Thank you!

PS. `mask: undefined` leads to crash.

**Comment by diegormb06** [comment]
I do this: create a wrap for the input, pass mask (or don't) and verify if it has mask.
`
const Input = props.mask ? <TextInputMask /> : <DefaultTextInput>;
`

them return input;

**Comment by badkos** [comment]
Just don't pass a `mask` prop.
