### ISSUE TITLE
Not working on modal

### ISSUE THREAD

**Issue by joseluismurillorios** [react-native-text-input-mask/react-native-text-input-mask#173]
# Bug report
10-08 17:37:04.169 27705 27705 E AndroidRuntime: FATAL EXCEPTION: main
10-08 17:37:04.169 27705 27705 E AndroidRuntime: Process: com.pospaypointapp.real, PID: 27705
10-08 17:37:04.169 27705 27705 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-08 17:37:04.169 27705 27705 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        ... 1 more
10-08 17:37:04.169 27705 27705 E AndroidRuntime: Caused by: com.redmadrobot.inputmask.helper.Compiler$FormatError
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at com.redmadrobot.inputmask.helper.Compiler.compileWithCustomNotations(Compiler.kt:307)
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at com.redmadrobot.inputmask.helper.Compiler.compile(Compiler.kt:243)
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at com.redmadrobot.inputmask.helper.Compiler.compile(Compiler.kt:111)
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at com.redmadrobot.inputmask.helper.Compiler.compile(Compiler.kt:93)
10-08 17:37:04.169 27705 27705 E AndroidRuntime:        at com.redmadrobot.inputmask.helper.Mask.<init>(Mask.kt:95)

## Summary
I'm using the input mask on a modal with a tabview, whatever value is entered makes the app crash. It works correctly in other parts of the application.

![image](https://user-images.githubusercontent.com/11035303/95530164-ff1e0f00-0991-11eb-922c-960004e41085.png)

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 84.83 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 28, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.1
      System Images: android-23 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.0 4.0
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native: 0.61.1
```

Library version: x.x.x

## Steps to reproduce

1. Create a modal (react-native-modal)
2. Create a tab view (react-native-tab-view)
3. Add an input mask component and enter a value

Describe what you expected to happen:

1. ...

## Reproducible sample code

```react
<InputMask
  keyboardType="numeric"
  mask="[9990.00]"
  placeholder="0.00"
  onChange={(text) => { setStartingCash(text); }}
  value={startingCash}
/>
```

**Comment by martintreurnicht** [comment]
My guess is `onChange` should be `onChangeText`
