### ISSUE TITLE
App Crash After install Dependencies

### ISSUE THREAD

**Issue by shiroze** [react-native-text-input-mask/react-native-text-input-mask#175]
Android App crash after add / install dependencies `yarn add` and `npm install`
```
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-text-input-mask": "2.0.0",

```

Any solution ?

**Comment by Navipro70** [comment]
Did you add this lines to your Podfile after `target ${YourAppName} do` ?

```
use_frameworks!
pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
```

If not, you should add them and then run `pod install`

If you have big error after pods installation, try remove line `use_frameworks!` 

After this you should restart your simulator.

**Comment by shiroze** [comment]
> Did you add this lines to your Podfile after `target ${YourAppName} do` ?
> 
> ```
> use_frameworks!
> pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
> ```
> 
> If not, you should add them and then run `pod install`
> 
> If you have big error after pods installation, try remove line `use_frameworks!`
> 
> After this you should restart your simulator.

this problem on Android

**Comment by Navipro70** [comment]
I have same versions of dependencies and all works perfect.

1. Can you provide additional information please (from your terminal maybe)?
2. Try clear cache `cd android && ./gradlew clean`
3. Are you sure that problem exist in this library?

**Comment by shiroze** [comment]
> Sorry, I have same versions of dependencies and all works perfect on Android.
> 
> 1. Can you provide additional information please (from your terminal maybe)?
> 2. Try clear cache `cd android && ./gradlew clean`
> 3. Are you sure that problem exist in this library?

gradlew clean solve the problem thank you.
