### ISSUE TITLE
[Feature] RightToLeft prop missing

### ISSUE THREAD

**Issue by jeancatarina** [react-native-text-input-mask/react-native-text-input-mask#176]
Hello, the library input-mask-ios and input-mask-android has created a prop to be able to type from right to left. Do you have any prediction of when it will be implemented here?

- https://github.com/RedMadRobot/input-mask-ios/wiki/2.2-Right-to-Left-&-Digit-Grouping
- https://github.com/RedMadRobot/input-mask-ios/wiki/2.-Text-Field-Listener

**Comment by AlphaJuliettOmega** [comment]
Yes please, is it possible to type a number RTL (like normal monetary inputs) without this feature?

**Comment by martintreurnicht** [comment]
You are welcome to submit a PR for this feature.

**Comment by martintreurnicht** [comment]
Now supported, check out https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.1.1
