### ISSUE TITLE
Space and special characters

### ISSUE THREAD

**Issue by AnnaCarolinaWGC** [react-native-text-input-mask/react-native-text-input-mask#179]
Hello!
I'd like to know if there's a way of allowing the user to put characters like @!#>< on the input camp at his own deliberation. I've tried using [-----] or [_____] like the input-mask-android link recommended, but to no results yet.
If anyone knows if it's possible (and how), i'd like to know!
Thank you!

**Comment by martintreurnicht** [comment]
This is simply a wrapper around https://github.com/RedMadRobot/input-mask-ios and https://github.com/RedMadRobot/input-mask-android, if you have questions about the inner workings, i'd recommend contacting the original authors over at https://github.com/RedMadRobot. Alternatively, you are welcome to submit a PR
