### ISSUE TITLE
Is there a way to check if the mask has been satisfied?

### ISSUE THREAD

**Issue by spmorr01** [react-native-text-input-mask/react-native-text-input-mask#182]
Combing through the documentation/wiki on the link iOS project, it appears that there is a delegate for 'didFillMandatoryCharacters'. Is there something likewise to take an advantage of in the react native side of things?

Example: [9000] - Once I add 3 digits, is there something to tell me that they have satisfied the required amount of digits?

**Comment by martintreurnicht** [comment]
@spmorr01 Most of the heavy lifting is happening in https://github.com/RedMadRobot/input-mask-ios. This is simply a `react-native` wrapper around that library. What you're talking about sounds more like validation to me anyway, for that i'd recommend using something like https://github.com/formium/formik. Or you could simply evaluate the values returned in `onChangeText` and manually check that it has the desired length. Either way it is out of scope for this library
