### ISSUE TITLE
[Android] Characters are duplicating on production env sometimes

### ISSUE THREAD

**Issue by SrBrahma** [react-native-text-input-mask/react-native-text-input-mask#183]

**Comment by martintreurnicht** [comment]
@SrBrahma Can you verify that this is still happening on [v3](https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.0)? If not, please close this issue.

**Comment by SrBrahma** [comment]
Ok. Will soon update my app with it, and when live I will test it. I ain't sure if it would happen on "react-native run-android --variant=release", but on real prod it was happening.

In up a week I will update the status here.

**Comment by SrBrahma** [comment]
Issue progress blocked by https://github.com/react-native-text-input-mask/react-native-text-input-mask/issues/189

**Comment by martintreurnicht** [comment]
Yeah sorry about that, should be fixed in https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.1

**Comment by martintreurnicht** [comment]
@SrBrahma I'm closing this issue for now, if it is still happening, please feel free to re-open this issue
