### ISSUE TITLE
Android and ios Not Working

### ISSUE THREAD

**Issue by metion** [react-native-text-input-mask/react-native-text-input-mask#185]
[Mon Mar 01 2021 17:55:24.694]  ERROR    TypeError: null is not an object (evaluating 'RNTextInputMask.mask')
[Mon Mar 01 2021 17:55:24.695]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Mon Mar 01 2021 17:55:24.695]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by fatmali** [comment]
I can't even install it from npm, too many type errors.

**Comment by Bilal-Abdeen** [comment]
1. I suggest changing the issue title to "TypeError: null is not an object (evaluating 'RNTextInputMask.mask')"
2. I tried the following to reset and rebuild the app. It did NOT work. 
```
rd %localappdata%\Temp\metro-cache /s /q & del %localappdata%\Temp\haste-map* & cd android & gradlew clean & cd .. 
rd node_modules /q /s
npm cache clean --force 
npm install
```

**Comment by unfernandito** [comment]
@fatmali @Bilal-Abdeen @metion Which version of this library are using?

**Comment by fatmali** [comment]
3.0.0, the most recent one.

**Comment by unfernandito** [comment]
Hello @fatmali Did you installed some old version time ago?

Could be a cache problem in our systems

**Comment by Bilal-Abdeen** [comment]
@unfernandito 
I have been using this library for a while with no problems. Yesterday, I rebuilt my app, and consequently got the latest version. I got the error messages above, which @metion mentioned.

**Comment by unfernandito** [comment]
Can you try roll back to the last working version of this library in your app?

I think they made a major change in the lasts days and some documentation was not added.

**Comment by unfernandito** [comment]
Yes, they added this piece of code:

https://github.com/react-native-text-input-mask/react-native-text-input-mask/commit/26698c74fad67e139c54126495cbe3c30ee8c214

**Comment by unfernandito** [comment]
Hello.

Could try this missing step?

https://github.com/react-native-text-input-mask/react-native-text-input-mask/pull/188/commits/6f0352560fca3a1f2efaa4ce781b1ad77acd5289#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R36

If you receive any error from this step, see into the module package folder cause i think npm it's not fetching the ios & android native modules, if you don't see the ios and android folder, try install a previous version and follow the same step.

Best regards

**Comment by jacob3794** [comment]
Receiving the error after adding that and running `pod install` after clearing yarn/metro cache for the latest version

```
[!] No podspec found for `RNInputMask` in `../node_modules/react-native-text-input-mask/ios/InputMask`
```

I've not had any issues from using `^2.0.0`.

**Comment by malmyros** [comment]
I have the same issue with everyone above. What is the recommended version prior to this issue?

**Comment by unfernandito** [comment]
Try to use a previous version of this lib and add the next line in your Podfile below of `use_frameworks!`:

`pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`

**Comment by malmyros** [comment]
> Try to use a previous version of this lib and add the next line in your Podfile below of `use_frameworks!`:
> 
> `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`

Thank you, I installed both version 2.0.0 and 2.0.1. 

In the end I got it working but unfortunately there is quite a few issues with it for my use case and I had to remove it. I might look at again in the future.

**Comment by unfernandito** [comment]
> > Try to use a previous version of this lib and add the next line in your Podfile below of `use_frameworks!`:
> > `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`
> 
> Thank you, I installed both version 2.0.0 and 2.0.1.
> 
> In the end I got it working but unfortunately there is quite a few issues with it for my use case and I had to remove it. I might look at again in the future.

Sad to hear this 😢

**Comment by martintreurnicht** [comment]
Fixed in https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.1
