### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by danish-blueeast** [react-native-text-input-mask/react-native-text-input-mask#186]
## Description
getting error on `yarn add react-native-text-input-mask`. Other packages installing perfectly.

## Screenshots :

![Screenshot from 2021-03-02 15-26-51](https://user-images.githubusercontent.com/76940604/109635072-c6aee580-7b6b-11eb-905f-15a7257c7a15.png)

![Screenshot from 2021-03-02 15-58-26](https://user-images.githubusercontent.com/76940604/109638725-2b6c3f00-7b70-11eb-8b21-e61b8ea5e8a1.png)

**Comment by viktorgama** [comment]
same issue here

**Comment by pablomoroni** [comment]
same issue

**Comment by danish-blueeast** [comment]
any update ??

**Comment by WeslleyNasRocha** [comment]
I've got some more output:
```shell
error /home/weslley-rocha/projects/****/node_modules/react-native-text-input-mask: Command failed.
Exit code: 1
Command: npx tsc
Arguments: 
Directory: /home/weslley-rocha/projects/****/node_modules/react-native-text-input-mask
Output:
npx: instalou 1 em 0.866s
error TS5023: Unknown compiler option 'allowSyntheticDefaultImports'.
error TS5023: Unknown compiler option 'jsx'.
error TS5023: Unknown compiler option 'lib'.
error TS5023: Unknown compiler option 'moduleResolution'.
error TS5023: Unknown compiler option 'skipLibCheck'.
```

**Comment by brisingrBase** [comment]
same issue!

**Comment by artmerlop** [comment]
Same issue, any fix for this?

**Comment by GustavoEklund** [comment]
same issue

**Comment by DwCleb** [comment]
have no one a workaround? I'm with same issue and cant install

**Comment by yawnr** [comment]
I ended up forking it and removing the `postinstall` and changing main to `"main": "index.tsx",`

That should at least fix the install process

**Comment by rpc1910** [comment]
same problem

**Comment by Jeontaeyun** [comment]
Same Problem :(

**Comment by Jeontaeyun** [comment]
We need to use version 2.0.1 at moment 
```bash
$yarn add react-native-text-input-mask@2.0.1
```

**Comment by martintreurnicht** [comment]
Fixed in https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.1
