### ISSUE TITLE
[3.0.0, Android] "Cannot read property 'mask' of null" [hermes issue maybe?]

### ISSUE THREAD

**Issue by SrBrahma** [react-native-text-input-mask/react-native-text-input-mask#189]
I didn't change the code, just installed new major version. Tried to remove and install it again, tried to `npx react-native-clean-project`, `npm run android` again, reopened app... Error still happening.

```
[Wed Mar 03 2021 22:51:09.180]  ERROR    TypeError: Cannot read property 'mask' of null, js engine: hermes
[Wed Mar 03 2021 22:51:09.184]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
[Wed Mar 03 2021 22:51:09.186]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
```
Versions:

"react-native": "^0.63.4",
"hermes-engine": "^0.5.2-rc1",
"react-native-text-input-mask": "^3.0.0",

I will for now keep using the package previous version.

**Comment by martintreurnicht** [comment]
Should be fixed in https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.1
