### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNTextInputMask.mask') in v3.0.0

### ISSUE THREAD

**Issue by Bohilc** [react-native-text-input-mask/react-native-text-input-mask#191]
I have got this error after installing the package.
In package.json: `"react-native-text-input-mask": "^3.0.0",`
I thought it was fixed in the issue: https://github.com/react-native-text-input-mask/react-native-text-input-mask/issues/156 but the error still exists.

<img width="562" alt="obraz" src="https://user-images.githubusercontent.com/29238597/110236770-fda04500-7f37-11eb-9e2f-3c08a6665f47.png">

**Comment by mksglu** [comment]
same

**Comment by mksglu** [comment]
same error with me
![image](https://user-images.githubusercontent.com/6067714/110240083-41587600-7f5b-11eb-9c89-c173a167acb0.png)

**Comment by olya-ivanochko** [comment]
NO android, ios folder after `yarn add react-native-text-input-mask`
Only happens in v3.0.0. Please fix this asap

**Comment by HADEERALy** [comment]
if you use react native cli then 
1.npm uninstall react-native-text-input-mask
 2. use 0.3.2 version – npm install --save react-native-text-input-mask@0.3.2
 or  yarn add react-native-text-input-mask@0.3.2
 3.npx react-native run-android
it worked fine with me in android 

this package won't work for expo I tested it so many times 
so I used another package =>  npm i react-native-masked-text

**Comment by parkcoop** [comment]
This is still an issue in 3.0.3

**Comment by parkcoop** [comment]
OKAY IT WORKS NOW (without use_frameworks!)
- installed latest 3.0.3
- add this line to pod file
`  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true`
- pod install

Finally built successfully on iOS

**Comment by csppopa** [comment]
parkcoop workaround/fix works

**Comment by martintreurnicht** [comment]
> same error with me
> ![image](https://user-images.githubusercontent.com/6067714/110240083-41587600-7f5b-11eb-9c89-c173a167acb0.png)
> 
> and when adding these lines in my podfile i got an error:
> 
> ```
>  use_frameworks!
>  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
> ```
> 
> `` [!] No podspec found for `RNInputMask` in `../node_modules/react-native-text-input-mask/ios/InputMask ``

You don't need to add the podspec manually, autolinking should just do this for you, but if you did it manually you're using the wrong path, the spec is in the root directory

**Comment by martintreurnicht** [comment]
> NO android, ios folder after `yarn add react-native-text-input-mask`
> Only happens in v3.0.0. Please fix this asap

This has been resolved in latest version

**Comment by martintreurnicht** [comment]
> OKAY IT WORKS NOW (without use_frameworks!)
> 
> * installed latest 3.0.3
> * add this line to pod file
>   `  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true`
> * pod install
> 
> Finally built successfully on iOS

Not sure why you need modular headers here, just adding `use_frameworks!` should be good enough. I don't think you can build this without `use_frameworks!` as this project is written in swift and frameworks are required

**Comment by martintreurnicht** [comment]
Closing this issue as it seems that the original issue was related to ios/android folders not included in npm package. That issue has been fixed several versions back.

**Comment by ZeeshanAhmadKhalil** [comment]
> * pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

where in podfile?

**Comment by Grumbash** [comment]
@ZeeshanAhmadKhalil 
Try to set it right after `config = use_native_modules!`. 
Works for me
```target 'YourAppName' do
  config = use_native_modules!

  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )



  target 'YourAppNameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

**Comment by vasylnahuliak** [comment]
> just adding `use_frameworks!` should be good enough

https://fbflipper.com/docs/getting-started/ios-native/#cocoapods

https://github.dev/facebook/react-native/blob/2e8893fb5be0c877e0818d04264d75fa92ae0f8e/template/ios/Podfile

If you have `use_frameworks!` enabled, Flipper will not work

**Comment by ZubairovSalim** [comment]
Manual linking for android resolved issue!
