### ISSUE TITLE
onFocus and onBlur events not firing when component given a mask prop

### ISSUE THREAD

**Issue by yawnr** [react-native-text-input-mask/react-native-text-input-mask#192]
Upgrading to `v3.0.0` and running into some issues. Lots of stuff is working great, but passing a `mask` prop causes the `onFocus` and `onBlur` callbacks to not be invoked.

Examples:
```
    <TextInputMask
          mask="[0000]"
          style={{ fontSize: 20, backgroundColor: 'red' }}
          onFocus={() => {
            console.log('I don\'t work');
          }}
          onBlur={() => {
            console.log('Neither do I');
          }}
    />

    <TextInputMask
          style={{ fontSize: 20, backgroundColor: 'green' }}
          onFocus={() => {
            console.log('I work!');
          }}
          onBlur={() => {
            console.log('So do I!');
          }}
    />
```

Also, unrelated, it probably doesn't make sense to have an `npx tsc` `postinstall` script

**Comment by martintreurnicht** [comment]
This could be related to rewiring of listeners in the native code, is this happening on iOS, android or both?

**Comment by martintreurnicht** [comment]
Also, recent release has fixed up packaging, check out https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.1

**Comment by Hapsidra** [comment]
I only tested on android and it happens here

**Comment by yawnr** [comment]
I was on iOS, so it appears it's on both platforms

**Comment by KornobisD** [comment]
any updates on that problem? We are facing the same issue on both platforms

**Comment by martintreurnicht** [comment]
@yawnr This should now be resolved in https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.4 for both android and iOS
