### ISSUE TITLE
Auto delete 7 after 7

### ISSUE THREAD

**Issue by Azshar** [react-native-text-input-mask/react-native-text-input-mask#193]
Hi! 
I have a mask on input, like that mask={'+7 | ([000])[000]-[00]-[00]'}. If i want to enter the number 7, it's automatically deleted.

**Comment by martintreurnicht** [comment]
Masking behavior is not controlled by this library, we're simply adding a wrapper for ReactNative. For questions on native masking behavior, reach i'd recommend reaching out to the native maintainers at https://github.com/RedMadRobot
