### ISSUE TITLE
Cursor is jumping when delete symbols from the middle of value

### ISSUE THREAD

**Issue by abramovslava** [react-native-text-input-mask/react-native-text-input-mask#194]
**Problem:**
When use `value` property, that goes from state variable, and delete characters from the middle of value, cursor is jumping to last character.

Please, take a look at the attached gif:
![20210311_101727](https://user-images.githubusercontent.com/20501714/110759952-3e150100-825f-11eb-9106-3283cf0d4bf5.gif)

OS: `Android`
Version: `2.0.1`

**How to reproduce:**
Example of code:

```
const App = () => {
  const [value, setValue] = useState('');

  const onChangeText = useCallback(
    (formatted: string) => setValue(formatted),
    [],
  );

  return (
    <SafeAreaView>
      <ScrollView>
        <View>
          <TextInputMask
            value={value}
            onChangeText={onChangeText}
            mask={'+1 ([000]) [000] [00] [00]'}
            style={styles.input}
          />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};
```

Repo to reproduce: https://github.com/abramovslava/jumping-cursor-react-native-text-input-mask

**Comment by martintreurnicht** [comment]
This is probably due to autocomplete behavior, try switching it off and see if solves your problem:

```jsx
<TextInputMask autocomplete={false}, autoskip={false} />
```

**Comment by gron01** [comment]
> This is probably due to autocomplete behavior, try switching it off and see if solves your problem:
> 
> ```js
> <TextInputMask autocomplete={false}, autoskip={false} />
> ```

I've done these, but the problem still persists.

**Comment by abramovslava** [comment]
Sorry for late answer...

@martintreurnicht i can confirm that even with `autocomplete` and `autoskip` properties issue still persists. I`ve updated repo with these properties.

**Comment by martintreurnicht** [comment]
@abramovslava Ok i see, you're using version 2. That version is no longer supported, it was created by the previous maintainer, please upgrade to the latest version. I can confirm that it no longer happens on the latest

**Comment by Rodrigo816** [comment]
This still happens on v3.1.4

**Comment by 7dp** [comment]
still jumping on v3.1.4

**Comment by akimabs** [comment]
any update for this issue ?

version 3.1.4 on android, this issue still jumping, but on 3.1.2 this issue was resolved

but, on ios get the other error

**Comment by acollazomayer** [comment]
Same issue on 3.1.4
