### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by Breners** [react-native-text-input-mask/react-native-text-input-mask#196]
The 'Pods-psibankapp' target has transitive dependencies that include statically linked binaries: (/Users/brenerdev/Documents/GitHub/TFS_Psibank_App/psibankapp/ios/Pods/CocoaLibEvent/lib/libevent.a, /Users/brenerdev/Documents/GitHub/TFS_Psibank_App/psibankapp/ios/Pods/CocoaLibEvent/lib/libevent_core.a, /Users/brenerdev/Documents/GitHub/TFS_Psibank_App/psibankapp/ios/Pods/CocoaLibEvent/lib/libevent_extra.a, /Users/brenerdev/Documents/GitHub/TFS_Psibank_App/psibankapp/ios/Pods/CocoaLibEvent/lib/libevent_pthreads.a, /Users/brenerdev/Documents/GitHub/TFS_Psibank_App/psibankapp/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a, and /Users/brenerdev/Documents/GitHub/TFS_Psibank_App/psibankapp/ios/Pods/OpenSSL-Universal/ios/lib/libssl.a)

this error is after use_frameworks on Podfile, someone can help me

**Comment by star-collector** [comment]
Try adding this in Podfile for your target:


`pre_install do |installer|`
`Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}`
`end`

**Comment by alexandreaugus** [comment]
I am also having trouble with RN 0.63.4
<img width="394" alt="Screen Shot 2021-03-18 at 11 30 37" src="https://user-images.githubusercontent.com/58692612/111643275-99a23a00-87dd-11eb-9fa5-e6dc64a5ec8d.png">

**Comment by martintreurnicht** [comment]
This is probably because of Pods that was included incorrectly before, try this release https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.3
