### ISSUE TITLE
Out of the box support for custom notations 

### ISSUE THREAD

**Issue by parkcoop** [react-native-text-input-mask/react-native-text-input-mask#198]
Looking through readme, I do not see any reference to custom notations as discussed in the Red Mad Robot wikis, is there a proper way to do this through the react-native-text-input mask API? I see previous people have asked similar questions but only to have the issues closed with no response. 

Would like to know if this is supported without modifying swift/java code

**Comment by parkcoop** [comment]
will PR

**Comment by martintreurnicht** [comment]
I've been looking into exposing more of the underlying properties of the input mask listener, if you want to send a PR i'd be happy to review.

**Comment by martintreurnicht** [comment]
Now supported, check out https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.1.1
