### ISSUE TITLE
pod install error on ios

### ISSUE THREAD

**Issue by csppopa** [react-native-text-input-mask/react-native-text-input-mask#200]
when doing pod install i get the following error:
[!] The target has transitive dependencies that include statically linked binaries: 

1. from what i read on the internet it is because of 'use_frameworks!'

if i remove 'use_frameworks!' i get the following error:

2. [!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `react-native-text-input-mask` depends upon `React-RCTText`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

version: 3.0.3
platform: ios

**Comment by csppopa** [comment]
UPDATE:

the second error can be solved exactly like here while the problem is fixed: 

https://github.com/react-native-text-input-mask/react-native-text-input-mask/issues/191#issuecomment-803368920

**Comment by martintreurnicht** [comment]
As per the documentation, `use_frameworks!` is the recommended way to use it, If you're having an issue with `use_frameworks!` as part of your project, that is outside the scope of this project.

**Comment by kadirfurkanguler** [comment]
add this line your podfile under the
` use_Flipper!()`
`use_modular_headers!` # <-Add this line

**Comment by samuelprogramer** [comment]
I fixed this issue by doing the following
instal the

`yarn add react-native-text-input-mask`

then put it in ios/podfile

`pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true`

Any question go to the readem.md of the react-native-text-input-mask library in your node_modules, it has the information you shoud use
