### ISSUE TITLE
don't set the value in field

### ISSUE THREAD

**Issue by secodigo** [react-native-text-input-mask/react-native-text-input-mask#202]
I did tests and in latest version of react-native is not setting the value in the field

    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-text-input-mask": "^3.0.4"

follow example:

```
const App: () => Node = () => {
  const value = '+1 (123) 456-78-90';
  return (
    <>
      <TextInputMask
        value={value}
        onChangeText={(formatted, extracted) => {
          console.log(formatted); // +1 (123) 456-78-90
          console.log(extracted); // 1234567890
        }}
        mask={'+1 ([000]) [000] [00] [00]'}
      />
    </>
  );
};
```

**Comment by martintreurnicht** [comment]
Fixed in https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.1.2
