### ISSUE TITLE
Works bad when value property is set

### ISSUE THREAD

**Issue by yuoppp** [react-native-text-input-mask/react-native-text-input-mask#21]
```
this.state = {
       loginFormatted: '9111111111',
       login: '9111111111',
     };
  
   ......

   <TextInputMask
                    onChangeText={(formatted, extracted) => {
                      this.setState({login: extracted, loginFormatted: formatted});
                    }}
                    mask={"[000] [000] [00] [00]"}
                    value={this.state.loginFormatted}
                    keyboardType="numeric"
                  />
   
```

Here is my code.
When i start typing, the input value changes, then changes back to previous for a moment and then becomes right.

For example:

-- value was: 123 45
-- I type '6' 
-- value becomes 123 456
-- value becomes 123 45
-- value becomes 123 456

Probably state doesn't change fast enough.
This ui changes are very noticeable for user. 

Is there any workaround for it?

**Comment by yuoppp** [comment]
Sorry.
Dupe of #11

**Comment by yuoppp** [comment]
using v0.5.2

But still, when i try to delete the separator char it appears again.

mask is: `"[000] [000] [00] [00]"`
value is:  911_111_1|

where '|' is caret and _ is a space char

pressed backspace: 911 111_
pressed backspace again: 911 111_
pressed one more time: 911 111

It would be great to trim separator chars before returning the formated value

**Comment by valerybugakov** [comment]
@yuoppp did you figure out how to fix that?

**Comment by tempname11** [comment]
@yuoppp @valerybugakov using the input as uncontrolled (no re-renders on onChangeText) fixes this for me. This is a bit unfortunate, since you have to worry about the values getting out of sync, but at least the user experience is OK.

**Comment by Daniyal857** [comment]
I'm also facing the same issue.
version I used:
"react-native-text-input-mask": "^1.0.6",
"react-native": "0.60.5",


`<TextInputMask
                                            refInput={ref => { this.input = ref }}
                                            value={this.state.phone}
                                            onChangeText={(formatted, extracted) => this.setState({phone : extracted})}
                                            placeholderTextColor='#000'
                                            placeholder = "Phone *"
                                            keyboardType = "numeric"
                                            returnKeyType = "next"
                                            style={[styles.input, styles.inputTwo, {width:"70%",} ]}
                                            mask={"+1 ([000]) [000] [0000]"}
                                        />`

without value prop its working fine.

**Comment by martintreurnicht** [comment]
This should be fixed in [v3](https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.0)
