### ISSUE TITLE
[!] No podspec found for `RNInputMask` in `../node_modules/react-native-text-input-mask`

### ISSUE THREAD

**Issue by guisszo** [react-native-text-input-mask/react-native-text-input-mask#214]
In react native "0.63.3" when i upgrade "react-native-text-input-mask" from 2.0.0 to 3.1.4 i got this error:

``[!] No podspec found for `RNInputMask` in `../node_modules/react-native-text-input-mask``

i think this is due to the directory "InputMask" present in
`` ../node_modules/react-native-text-input-mask/ios/InputMask``
in version 2.0.0 which is not in the latest version
but when i downgrade again it works fine;

**Comment by VashaMasha** [comment]
Hello! I've got the same problem, but I have to use version > 3.0.0. So, resolving the issue by downgrading the version is not valid)))
How can i manage this problem without version changing?

**Comment by dustinyoste** [comment]
Remove `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'`
from the Podfile

**Comment by dustinyoste** [comment]
Remove both from `ios/Podfile`:
`pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'` 
`pod 'react-native-text-input-mask', :path => '../node_modules/react-native-text-input-mask'`

If upgrading from `2.0.0` you may need to add a `.swift` file to your project.
https://github.com/react-native-text-input-mask/react-native-text-input-mask/compare/v2.0.0...v3.1.4

**Comment by guisszo** [comment]
yes @dustinyoste  i removed ``pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'``  and added that: ``  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true
`` to my pod file and it is working fine now !! thank you very much
