### ISSUE TITLE
on 0.64.0 package doesn't work

### ISSUE THREAD

**Issue by beqramo** [react-native-text-input-mask/react-native-text-input-mask#220]
Hi, I tried to install this package on the latest react-native version with the solutions you have in the readme but none of them worked.

**Comment by kopax-polyconseil** [comment]
Same here

**Comment by i-yusuf** [comment]
open XCode
create new file, select swift file
confirm "Create Bridging Header"
clean and build (I actually made my first build from XCode and then from react-native CLI)

**Comment by beqramo** [comment]
@i-yusuf  I will try thanks, but as I remember I did that step.

**Comment by i-yusuf** [comment]
If you did that already try this:

- Go to ios folder and run
`pod deintegrate`

- Add this to podfile
`React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true`

- Go to ios folder and run
`pod install`

- Open XCode
- Create New File -> Swift
- Confirm 'Create Bridging Header'
- Product -> Clean Build Folder

- `npx react-native run-ios`

**Comment by beqramo** [comment]
thanks, I will try as soon as I will have time. and I will write the result  here

**Comment by beqramo** [comment]
it worked thanks, I will close it mow.

**Comment by beqramo** [comment]
it worked thanks, I will close it now.
