### ISSUE TITLE
iOS Archive Build Issue

### ISSUE THREAD

**Issue by nicoache1** [react-native-text-input-mask/react-native-text-input-mask#229]
#### Description

When i tried to make a new archive in the xcode the build fails with the next errors

![Screen Shot 2021-05-13 at 17 14 23](https://user-images.githubusercontent.com/26419582/118181884-ae323580-b40e-11eb-9468-1865796d8d82.png)

#### Environment

``` 
Versions:

react-native: 0.63.4,
react: 16.13.1,
react-native-text-input-mask: 3.1.4
Xcode 12.4
iOS Catalina.

```

```
PODFILE

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

project 'reactNativeDroccoLandscaping',
    'Debug' => :debug,
    'Release' => :release,
    'Staging' => :release

target 'reactNativeDroccoLandscaping' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) 
  post_install do |installer|
    flipper_post_install(installer)
  end
end

```

#### Expected Behaviour

Archive should be successful

**Comment by davidkhuu** [comment]
This comment seemed to work for me: https://github.com/facebook/react-native/issues/28503#issuecomment-624785816

I was getting the same error. My Podfile platform is `11.0` like yours but my target deployment was 10.0. Changing it to 11.0 to match my Podfile allowed my archive to complete successfully.

**Comment by nicoache1** [comment]
> This comment seemed to work for me: [facebook/react-native#28503 (comment)](https://github.com/facebook/react-native/issues/28503#issuecomment-624785816)
> 
> I was getting the same error. My Podfile platform is `11.0` like yours but my target deployment was 10.0. Changing it to 11.0 to match my Podfile allowed my archive to complete successfully.

Thanks a lo @davidkhuu that works like a charm!
