### ISSUE TITLE
Bug with changing mask

### ISSUE THREAD

**Issue by ugar0ff** [react-native-text-input-mask/react-native-text-input-mask#237]
I have imput with mask (f.e. [00]-[000])
Steps:
1) Filled few symbols (f.e. 11-)
2) Changed mask to [00]-[0000] (longer)
3) Filled input (f.e. 11-1111)
4) Removed foces from field
5) Tapped to field
Result: Data in input was changed to 11-111 (removed last symbol)

**Comment by martintreurnicht** [comment]
Changing mask has limitations, you should use `affineFormats` instead. See https://github.com/RedMadRobot/input-mask-ios/blob/master/Documentation/COOKBOOK.md#dates for examples

**Comment by JayantJoseph** [comment]
I am facing with the same issue
