### ISSUE TITLE
Error: NativeModule: RNTextInputMask is null.

### ISSUE THREAD

**Issue by mrsants** [react-native-text-input-mask/react-native-text-input-mask#289]
Pod is null

Error: NativeModule: RNTextInputMask is null.
To fix this issue try these steps:
  • Rebuild and restart the app.
  • Run the packager with `--clearCache` flag.
  • If happening on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.
  • If this happens while testing with Jest, make sure to follow instructions in https://github.com/react-native-text-input-mask/react-native-text-input-mask#testing
, js engine: hermes

**Comment by sierra-fox-app** [comment]
I am using an expo managed workflow and get the same error. It looks like react-native-text-input-mask installed succesfully, but then the above error surfaces.

The above troubleshooting steps did not resolve, and neither did expo start --clear.

has anyone found a solution?
