### ISSUE TITLE
Cannot read property 'mask' of undefined

### ISSUE THREAD

**Issue by adirzoari** [react-native-text-input-mask/react-native-text-input-mask#31]
I get this error 

> Cannot read property 'mask' of undefined

 when I add this line

> import TextInputMask from 'react-native-text-input-mask';

any solution?

**Comment by idrakimuhamad** [comment]
I got that error when I try to run my app, right after `npm install` the package. Maybe to stop your current build, do the necessary drag and drop and the rebuild your app

**Comment by lfkwtz** [comment]
Reference this updated readme --> #28

**Comment by GituBojan** [comment]
follwed your readme
still experience this error

import TextInputMask from 'react-native-text-input-mask';

**Comment by pipinov** [comment]
For android:

add to android/app/src/main/java/com/project_name/MainApplication.java

```
import com.RNTextInputMask.RNTextInputMaskPackage;
```

and add new RNTextInputMaskPackage() to getPackages

```
 protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
      new RNTextInputMaskPackage()
    );
  }
```

and make sure that you are linking package with command

```
react-native link react-native-text-input-mask
```

**Comment by WeiLiangTan** [comment]
I also facing the same issue. 

Added InputMask framework to Embedded Binaries on xcode.

Tried `react-native link`, but doesn't work. 

Any updates on this issue would be a great help. Thanks

**Comment by anvaskes** [comment]
Faced same issue, removed node modules, unlinked mask lib, reinstalled node modules, linked lib ( and relinked other ) , dragged lib to embedded lib's, set 'always embed' to yes. And it start to work

**Comment by lfkwtz** [comment]
@Komalov https://github.com/react-native-community/react-native-text-input-mask/issues/17#issuecomment-348833469

**Comment by LucasMMota** [comment]
Perfectly working on android, but not working on IOS, I'm getting same error 
Cannot read property 'mask' of undefined.
I've already add binary on xcode. I don't know what to do.

**Comment by aertmann** [comment]
Had same issue on iOS and found a solution.

"Embedded Binaries in General tab of Target and check ‘Yes’ in ‘Always Embed Swift Standard Libraries’ of Build Settings." didn't work for me. But after doing this and building the project I got a new file called `libRNTextInputMask.a` that I could select in "Linked Frameworks and Libraries". Could even remove the framework again.

Maybe this helps someone else. Could be the compilation just didn't work in my project for some reason.

**Comment by aloneszjl** [comment]
@aertmann https://github.com/react-native-community/react-native-text-input-mask/issues/73#issuecomment-439655769

**Comment by retyui** [comment]
I think we should add a human readable message like AsyncStorage:

https://github.com/react-native-community/async-storage/blob/9aad474ff7ca64d34ef94358a39205a609455aca/lib/AsyncStorage.js#L21-L38

https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md

**Comment by martintreurnicht** [comment]
Addressed in https://github.com/react-native-text-input-mask/react-native-text-input-mask/pull/184
