### ISSUE TITLE
How to set a value to TextInputMask component?

### ISSUE THREAD

**Issue by llvc** [react-native-text-input-mask/react-native-text-input-mask#33]
I am going to make the TextInputMask component not to be editable and show a formatted phone number, +86 1234 56 7890, by providing a pure number, 1234567890, on it.
And I want to clear the phone number sometimes.
I tried to set a value property or call `this.input.clear()`
But all of them were fallen in to fail.
Is there any way to implement?
Thanks.

**Comment by JonathanRufino** [comment]
Have you tried using a state variable and then updating it to an empty string?

**Comment by ideerge** [comment]
> Have you tried using a state variable and then updating it to an empty string?

doesnt work

**Comment by raza2022** [comment]
> phone

@llvc I am trying the same and I don't want to update it, how do you achive the disabled/not editable input?

**Comment by martintreurnicht** [comment]
This should be working now, please try the latest version
