### ISSUE TITLE
Library doesn't compile with RN 0.53.x and Cocoapods

### ISSUE THREAD

**Issue by MIREX** [react-native-text-input-mask/react-native-text-input-mask#37]
When i use Cocoapods and try to build project with XCode I always get the same error.

Steps to reproduce:
1) Create new project with `react-native init Test`
2) Add package with yarn: `yarn add react-native-text-input-mask`
3) Link library
4) Compile project - it's ok, compiles well!
5) Add Cocoapods into ios folder
6) Open .xcworkspace
7) Try compile again.

![2018-03-01 10 46 10](https://user-images.githubusercontent.com/1025141/36931887-99ad0e48-1ee1-11e8-81c8-7636cea6a70c.png)
![2018-03-01 10 41 50](https://user-images.githubusercontent.com/1025141/36931888-99cd8a92-1ee1-11e8-9e65-6143a64e96f8.png)

I think that there is something wrong with header search path, but don't even know how to fix it

**Comment by ivanzotov** [comment]
@MIREX thanks for reporting the issue, yes I'm working on it, as a temporary solution:

1. Choose cxxreact in `Product -> Scheme -> cxxreact`
2. Run build
3. Then switch scheme back and run build again

**Comment by IllyaVolkov** [comment]
Make sure you don't have InputMask.framework in Build Phases>Link Binary With Libraries

**Comment by IllyaVolkov** [comment]
@MIREX Probably I had incorrectly linked library manually.

**Comment by IllyaVolkov** [comment]
I found solution:
1. fix imports:
![screen shot 2018-03-03 at 17 04 21](https://user-images.githubusercontent.com/26715940/36935800-f04648dc-1f04-11e8-9cc8-b391ebfb87bd.png)
2. In RNTextInputMask.xcodeproj > Build Settings > Header Search Path
set path search mode to recursive
![screen shot 2018-03-03 at 17 06 43](https://user-images.githubusercontent.com/26715940/36935826-47f8082c-1f05-11e8-809b-ee35b96e85a1.png)

**Comment by MIREX** [comment]
@IllyaVolkov Thanks for this solution. But what about project without Cocoapods. Is it still compile?

**Comment by IllyaVolkov** [comment]
It runs both via react-native cli and via Xcode in production mode

**Comment by lyseiha** [comment]
+1
