### ISSUE TITLE
How can input minus symbol "-"

### ISSUE THREAD

**Issue by xuepx** [react-native-text-input-mask/react-native-text-input-mask#41]
I need degree mask and longitude mask, like +/-00°00′00.000000″ and 120°00′00.000000N/W.
now I can not input "-".

hope to your reply!

**Comment by betoharres** [comment]
Hi @xuepx I'm in the same situation right now, did you ever find out how to do this? I couldn't find any docs about negative numbers and I'm thinking about opening another issue :(

Thanks!
:smile:

**Comment by martintreurnicht** [comment]
For usage, please see https://github.com/RedMadRobot/input-mask-android and https://github.com/RedMadRobot/input-mask-ios
