### ISSUE TITLE
Change mask on the fly

### ISSUE THREAD

**Issue by bhd-vasyl** [react-native-text-input-mask/react-native-text-input-mask#42]
I need to change mask depending on country code
So if i have +44 the mask will be [99] [99] [9999] [9999]
And if i had +47 - [99] [99] [999] [999]
But when i trying to do that it doesn't work
```
  switch(countryCode) {
    case('44'):
      return this.setState({mask: '[99] [99] [9999] [9999]'})
    case('47'):
       return this.setState({mask: '[99] [99] [999] [999]'})
}
```

**Comment by yoavapi** [comment]
works for me, see my example:

	renderHomePhone() {
		let { homePhone } = this.state;
		let mask = "[00]-[0000000]"; //default
		let placeholder = "02-000000" //default
		if (!homePhone) homePhone = ""; //handle undefined 
		if (homePhone.substring(0, 2) == "07") {
			mask = "[000]-[0000000]"; //alternative mask
			placeholder = "070-000000" //alternative placeholder
		}
		return (<TextInputMask
			underlineColorAndroid="transparent"
			keyboardType="phone-pad"
			autoCapitalize="none"
			returnKeyType="done"
			onChangeText={this.onHomePhoneChanged()}
			value={homePhone}
			autoCorrect={false}
			placeholder={placeholder}
			mask={mask} />)
	}

	onHomePhoneChanged() {
		return (homePhone) => {
			this.setState({ homePhone });
		}
	}

**Comment by alpamys-qanybet** [comment]
@yoavapi, what is your version of release, I use 0.5.2 as later crashes.

**Comment by yoavapi** [comment]
@alpamys-qanybet 

I use 0.7.0

**Comment by martintreurnicht** [comment]
This should be working in the latest version
