### ISSUE TITLE
Android maxLength count the mask spaces

### ISSUE THREAD

**Issue by lucky-xiaohu** [react-native-text-input-mask/react-native-text-input-mask#46]
on android, maxLength prop count the mask space, for example, when set mask `[000000] [00000000] [0000]`, and set maxLength `18`, it work fine on iOS, I can input all of 18 valid characters, but on android, it is can only input 16 valid character, i must set maxLength to 20.

**Comment by cmejet** [comment]
Experiencing the same issue, going to try and make the maxLength platform specific for now, but that seems silly

**Comment by hkolsen** [comment]
Any progress on this?
