### ISSUE TITLE
Moving caret and disapearing characters

### ISSUE THREAD

**Issue by upils** [react-native-text-input-mask/react-native-text-input-mask#48]
On Android (I cannot test on iOS), when writting in the input, the caret is moving back to the input beginning (once the second character is written).
If I keep typing, characters at the end of the string are "pushed" by incoming ones, disapearing.
If I move my caret at the end of the string, I can type one character, then the caret is back to the beginning.

I'm testing with the example.

RN: 0.54.3
react-native-text-input-mask: 0.7.0

**Comment by KirillGudkov** [comment]
Same on RN: 0.56.0, react-native-text-input-mask: 0.8.0. IOS works properly

**Comment by martintreurnicht** [comment]
Should be fixed in latest version
