### ISSUE TITLE
How to install it manually?

### ISSUE THREAD

**Issue by suuzee** [react-native-text-input-mask/react-native-text-input-mask#54]
I refer to the tutorial and I know that I should run the `react-native link` command after installation. However, due to the different structure of our project directory, running `react-native link` does not make it work. So I want to know how to manually install this library to make it work?

Thanks!

**Comment by ivanzotov** [comment]
@suuzee linking the library is the same as documentation describe it https://facebook.github.io/react-native/docs/linking-libraries-ios, but you're right it should be available in the readme, will add documentation for manual installation soon, thanks!

**Comment by faustoct** [comment]
any idea how to solve this https://github.com/react-native-community/react-native-text-input-mask/issues/73

**Comment by faustoct** [comment]
following this https://github.com/react-native-community/react-native-text-input-mask/issues/54#issuecomment-406718514 does not solve
