### ISSUE TITLE
How to clear mask data when input is clear by the state?

### ISSUE THREAD

**Issue by surinder-enest** [react-native-text-input-mask/react-native-text-input-mask#62]
I'm using the input mask that is connected with **mobileNumber** from  component state.
some time i need to clear the **mobileNumber** so i'm using the blow code. number is cleared and sate is updated but the mask first view  **(**  stay in the input field i need to clear this when **mobileNumber** has empty string.  See Here:https://ibb.co/ehWMod
```
const clearNum()=>{
this.setState({
mobileNumber:''
})
}
```
```
<TextInputMask
                refInput={(ref) => this.myDateText = ref}
                mask={"([000]) [000]-[0000]"}
                placeholder="Mobile Phone"
                placeholderTextColor={lightGrayColor}
                underlineColorAndroid="transparent"
                keyboardType="numeric"
                style={homeStyles.PhoneInputText}
                maxLength={15}
                onChangeText={text => this.onTextChange(text)}
                value={mobileNumber}
              />
```

**Comment by artyorsh** [comment]
Fixed with love and available for [review](https://github.com/react-native-community/react-native-text-input-mask/pull/61)

**Comment by dharamEnest** [comment]
what i need to do for resolve this issue in my app ?

**Comment by artyorsh** [comment]
@dharamEnest 
I think nothing except waiting for pr approve🤞or copying changes from pr to your dependendies.

**Comment by dharamEnest** [comment]
ok Thanks @ivanzotov

**Comment by dharamEnest** [comment]
@ivanzotov @artyorsh  How i can use (fix mask/text update on rn v0.56)  code to test the functionality

**Comment by derenebdon** [comment]
I saw issues with the PR mentioned above and created my own "clear" fix: https://github.com/derenebdon/react-native-text-input-mask#fixClear exposes a clear method that you can call via a ref.  To use that branch, you simply use "react-native-text-input-mask": "git+https://github.com/derenebdon/react-native-text-input-mask.git#fixClear", in your package.json.

**Comment by johnh91** [comment]
> @dharamEnest thank you for the issue. I've tried to reproduce and saw the bug, will review the PR of @artyorsh and hope merge that.

Hi @ivanzotov, do we have any updates on this? I have the same issue and need the fix for the project on which I'm working

**Comment by yelenka** [comment]
Same for me, the mask is still visible once the number is deleted.
![image](https://user-images.githubusercontent.com/22195312/52817240-e9473200-3068-11e9-9041-05af715af479.png)

**Comment by igortupini** [comment]
I'm still having this issue as well

**Comment by tabekg** [comment]
> I'm still having this issue as well

Me too!

**Comment by igortupini** [comment]
This issue seems to be ignored for more than a year

**Comment by MateusCastro** [comment]
> This issue seems to be ignored for more than a year

The defaultValeu works like the value, there it works when clearing the state kkkkk
