### ISSUE TITLE
Extracted amount with decimal in currency mask?

### ISSUE THREAD

**Issue by andrewheekin** [react-native-text-input-mask/react-native-text-input-mask#69]
Is it possible to use the library to mask currency and have the extracted value include the decimal value?

For example, with a mask of `mask="$[9999].[99]"`, I'm getting a formatted value of something like `$1234.56` but an extracted value of `123456`. How could I make sure that extracted value is `1234.56`?

**Comment by donald-hanson** [comment]
I stumbled on to this with the same issue and I think this mask works with the decimal `[9999]{.}[99]`.

See https://github.com/RedMadRobot/input-mask-android#description for related documentation.
