### ISSUE TITLE
RNTextInputMask React/RCTBridge.h file not found

### ISSUE THREAD

**Issue by faustoct** [react-native-text-input-mask/react-native-text-input-mask#73]
After run:
````
yarn install react-native-text-input-mask
react-native link react-native-text-input-mask
````
got this error on xcode
`RNTextInputMask React/RCTBridge.h file not found`

How do I fix it?

**Comment by faustoct** [comment]
@ivanzotov any idea?

**Comment by faustoct** [comment]
couldn't find a solution so moved to https://github.com/benhurott/react-native-masked-text . when got a solution to this issue can go back to this plugin.. that seems quite better..

**Comment by faustoct** [comment]
I've searched around by couldn't find any solution that makes the project work. Do you guys have any suggestion? thank you in advance.

**Comment by faustoct** [comment]
Since I got the lib linked (I think so).. I got this error: `undefined is not an object (evaluating '_reactNative.NativeModules.RNTextInputMask.mask')` 
do you have any idea?

**Comment by faustoct** [comment]
anyone?!? I'm gonna look at this problem deeper.. finding anything will post here!

**Comment by iH04EP** [comment]
Add 'headers serach path' to your Build Settings.
I'm using 'expo' and this paths works for me : 

$(SRCROOT)/../../../../ios/Pods/Headers/Public
$(SRCROOT)/../../../../ios/Pods/Headers/Public/React

where $SRCROOT is {$my_project_dir}/node_modules/react-native-text-input-mask/ios/RNTextInputMask

don't forget "recursive" option for both paths. Something like this

{$your_project_dir}/ios/Pods/Headers/Public
{$your_project_dir}/ios/Pods/Headers/Public/React
You can set absolute paths to /Pods/Headers

**Comment by faustoct** [comment]
@iH04EP Hi and thank you. I think I did before, almost sure of that. I'm gonna try it in some hours and reply you..

**Comment by faustoct** [comment]
@iH04EP man.. I think I'm missing something. Just can't get this stuff working.. god!

**Comment by faustoct** [comment]
any other idea to get it working?

**Comment by lfkwtz** [comment]
did you do the `Always Embed Swift Standard Libraries` step from the readme?

**Comment by catamaican** [comment]
> 
> 
> Since I got the lib linked (I think so).. I got this error: `undefined is not an object (evaluating '_reactNative.NativeModules.RNTextInputMask.mask')`
> @ivanzotov , do you have any idea?

Confirm getting the same issue with a clean install

![image](https://user-images.githubusercontent.com/18305539/47267013-963ff100-d546-11e8-9930-6218bf831bbf.png)

**Comment by rodolfovilaca** [comment]
So, after much work done, i found a problem with the linking part of this library, which imported the wrong archives to my Libraries folder.

To fix that I've made the linking part myself on IOS(Android worked fine with the link). To do that, you right click your Libraries  folder in xcode, and select "Add Files to [your project name]", it will ask you which file you are willing to import... you go to your node_modules files in your project (assuming you already have added the react-native-text-input-mask and installed it) you find the react-native-text-input-mask project and search for `RNTextInputMask.xcodeproj`, click ok to import. Now you have this library imported in your project, and we must include it in the build phases. To do that you have to go to the "general" tab in xcode and drag and drop the libRNTextInputMask.a that is in the RNTextInputMask.xcodeproj > Products > ibRNTextInputMask.a to your "Linked Frameworks and Libraries". Clean your project and rebuild it, and its done.

It worked for me, idk if it will for everyone.

**Comment by jonathanmauer** [comment]
@rodolfovilaca Thank you so much! this works for me

**Comment by faustoct** [comment]
@lfkwtz can't even build the `react-native-text-input-mask` project on xcode. I have the same error `'React/RCTBridge.h' file not found`

**Comment by faustoct** [comment]
@lfkwtz @iH04EP @rodolfovilaca @iamandiradu just found a solution creating a podspec to this project. Which means it can be linked easily to react-native + deatch expo . However it requires migrate to SWIFT_VERSION which I already did , btw it has some compiler semantic issues and I don't know any about swift.. any can help with?!? so can create a pull-request to support project with specs:
````
Environment:
OS: macOS 10.14
Node: 9.8.0
Yarn: 1.5.1
npm: 5.6.0
Watchman: 4.9.0
Xcode: Xcode 10.1 Build version 10B61
Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
expo: ^30.0.1 => 30.0.1
react: 16.3.1 => 16.3.1
react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

app's target: iOS/Xcode10/ExpoKit/Detach
````
 [The repo you can download to help me (if have time)](https://github.com/faustoct/react-native-expo-text-input-mask/blob/master/README.md)

**Comment by frangeris** [comment]
@faustoct I just get exactly to this point without notice that you've made exactly the same :|

`React/RCTBridge.h` is not being found from Pods, migrating this package to Pods resolve this.

The second error is `InputMask` not found, adding to the `.podspec` resolve this:

```
  s.dependency          'InputMask'
```

And the last one is this semantic issue, I dont know how to continue from this.

![image](https://user-images.githubusercontent.com/811381/54649841-93f8a900-4a8a-11e9-8237-5106153d75bf.png) 

Any guidance? How did you end resolving this?

Thanks 🙏 

_PS: I've tested other packages but is not the same, others have some flickering issues..._

**Comment by raja-bounce** [comment]
anybody got the solution,  i am also facing the same issue.

**Comment by uiltonjose** [comment]
> anybody got the solution, i am also facing the same issue.

Still happening to me as well.

**Comment by k3ithl1m** [comment]
@frangeris what do you mean by migrating to pods

**Comment by ArkaneKhan** [comment]
adding this on build settings tab on header search path solved my problem
$(SRCROOT)/../node_modules/react-native-text-input-mask/ios

**Comment by josefdclxvi** [comment]
"react": "17.0.2",
"react-native": "0.67.2",
"react-native-text-input-mask": "^3.1.4"

same here, any solution for android?
