### ISSUE TITLE
Format Money Thousand Separator

### ISSUE THREAD

**Issue by SyntaxError001** [react-native-text-input-mask/react-native-text-input-mask#76]
Hi, good day! I have an inquiry about the formatter for Text Mask Input. All of the mask are working aside from the Money Format. I can't find a way to format money input. I want something to look like this:

1
12
123
1,234
12,345
123,456
1,234,567
12,345,678
123,456,789

Can you help me out about this issue? Please see attached picture below. Thank you so much in advance!
![screen shot 2018-09-25 at 2 15 08 pm](https://user-images.githubusercontent.com/43564319/45996345-7e538980-c0ce-11e8-8ec2-abcb2ab57c14.png)

**Comment by wesleyschneider** [comment]
Hi, I have the same problem. Have you found a solution?

**Comment by zahramemar** [comment]
Did you find any answer? I have same question

**Comment by vrinch** [comment]
you can use react-number-format

it works well, see below

````
              <NumberFormat
                value={amount}
                displayType={'text'}
                thousandSeparator={true}
                prefix={'$ '}
                renderText={value => (
                  <TextInput
                    underlineColorAndroid="transparent"
                    style={styles.input}
                    onChangeText={this.handleChange}
                    value={value}
                    keyboardType="numeric"
                  />
                )}
              />

 handleChange = amount => {
    this.setState({ amount })
  }
````
