### ISSUE TITLE
Doesn't work on iOS - undefined is not an object (evaluating ... NativeModules.RNTextInputMask.mask)

### ISSUE THREAD

**Issue by sryze** [react-native-text-input-mask/react-native-text-input-mask#83]
When I launch my iOS app I get the following error:

```
undefined is not an object (evaluating '_reactNative.NativeModules.RNTextInputMask.mask')
```

![error](https://user-images.githubusercontent.com/4525736/48800694-b7a61f80-ed34-11e8-9093-ebd8b40015ed.png)

I followed all the instructions in the README for iOS

1. added InputMask.framework to embedded binaries
2. enabled Always Embed Swift Standard Libraries

Do I need to do something else? It works fine on Android. 

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 34.05 MB / 16.00 GB
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.6.1
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

**Comment by rodolfovilaca** [comment]
You might have the same problem i had with the linking part on IOS, where it imported the wrong archives to my Libraries file. If it is this problem, you must do the linking part manually. I posted a step by step of what I did in this issue [#73](https://github.com/react-native-community/react-native-text-input-mask/issues/73#issuecomment-439655769)

**Comment by dogukankotan** [comment]
I used both linking and manual instructions. I had the same issue. After adding `libRNTextInputMask.a` to project's `Build Phases` ➜` Link Binary With Libraries`;
 it gives an error in build phase ` 'RCTText/RCTSinglelineTextInputView.h' file not found `.

I think it is related React Native versions, I'm using react-native 0.58.6. 
I also checked `<RCTText/RCTSinglelineTextInputView.h>` is also in react-native Libraries. However, cannot import it.
Reinstall the modules is not working also.
It was working on Xcode 9.4 by the way. I updated to Xcode 10.2 get the swift issue. Then I updated react-native-text-input-mask to 1.0.1. 

I will try to update react-native to 0.59.4.

**Comment by dogukankotan** [comment]
I found the solution. Make sure import of `libRNTextInputMask.a` after the `libRCTText.a`.
😄

Thanks. 
![Ekran Resmi 2019-04-11 11 50 33](https://user-images.githubusercontent.com/10637834/55946994-5b498b00-5c56-11e9-8bb7-46e4cdedb2b8.png)

**Comment by SamuelHiroyuki** [comment]
@dogukankotan I've tried importing but it still is not working. I did the whole linking process, but it shows me the same error yet. Did you do any more configuration on your project?

#### I'm using react-native-text-input-mask 1.0.1 n react-native 0.59.4 on macOS Mojave 10.14.3

![issue](https://user-images.githubusercontent.com/36797629/56317944-63149e00-6134-11e9-9003-ecedf2425117.png)

**Comment by Dietermartens** [comment]
same here!

**Comment by andrewhartwig** [comment]
Same here! 👍 @SamuelHiroyuki how do you hide the compiler warnings? I have to scroll down like 50 pages to find my errors :) 

Any solutions? I'm on RN 0.56 and am unable to update RN right now, but it seems people are having issues on the latest version anyways.

**Comment by SamuelHiroyuki** [comment]
@andrewhartwig you can use the filters at the left-bottom of the page.  ![image](https://user-images.githubusercontent.com/36797629/56516259-587d4e80-6510-11e9-8af1-e2bf7e341598.png)

I couldn't fix this problem. I can't downgrade the RN 0.59 because Apple only accept apps that are using IOS 12+ SDK.
