### ISSUE TITLE
Can't trigger onKeyPress event on iOS.

### ISSUE THREAD

**Issue by bob76828** [react-native-text-input-mask/react-native-text-input-mask#86]
My RN version is 0.57.
Does anyone has same issue?

**Comment by pratikafterpay** [comment]
@bob76828 Are you able to resolve this issue?
I am facing the same issue with onSelectionChange.
Will appreciate your help.

**Comment by fernandatoledo** [comment]
Hey! I'm still facing this issue, is there a fix for this?
